### ISSUE TITLE
ModuleNotFoundError: No module named 'xplnedsf2'

### ISSUE THREAD

**Issue by mendicus777** [nofaceinbook/ImportDSF-for-Blender#1]
Hi,

I think this is exactly what I am searching for, but regardless of Blender Version 2.8, 3.3, 3.6 - I always get 👍 

`ModuleNotFoundError: No module named 'xplnedsf2'`

Traceback (most recent call last):
  File "E:\Programme\Blender2.8LTS\2.83\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\xxx\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\ImportDSF-for-Blender-master\__init__.py", line 22, in <module>
    from .core.DSF_loader import DSF_loader
  File "C:\Users\xxx\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\ImportDSF-for-Blender-master\core\DSF_loader.py", line 2, in <module>
    from xplnedsf2 import *
ModuleNotFoundError: No module named 'xplnedsf2'

Am I missing something?

Thanks in advance!

**Comment by nofaceinbook** [comment]
Hi @mendicus777 thanks for trying out this import. First of all be warned that I did not finish this project and there is no way to transer performed changes in blender back to X-Plane. But in order to solve your problem it seems you did not copy/install the file xplnedsf2.py. It should be at the same location as the DSF_loader.py

**Comment by nofaceinbook** [comment]
Well, having the same issue on a new machine. Might be that some python modules need to be installed first. Try to have a look but not sure if I can fix it as a stopped development for X-Plane. Sorry.

**Comment by mendicus777** [comment]
Hi nofaceinbook,
thanks for your message - much appreciated.
I am not interested in an export, solely an Import. If you could look into the missing modules it would be great! Let me know, if I can assist in any way.
Thanks again!

**Comment by mendicus777** [comment]
I was able to fix the "ModuleNotFoundError"
It looks for the xplnedsf2 directly inside the addons folder. So if you place the script into there you can import it afterwards.
But now when trying to import the .dsf, I get this error:

<img width="662" alt="error" src="https://github.com/nofaceinbook/ImportDSF-for-Blender/assets/156319906/a2db7148-5aeb-4e51-acb1-26e712f95ab6">

Will have to examine the .dsf file. Not sure what the key 'sim/west' does.
Maybe you could simply skip that or provide a default value for this key ?

**Comment by nofaceinbook** [comment]
I did not understand how you solved it, but I created now an all in one script which should not produce import errors.
Do you have py7zlib installed in your blender python (not that easy but there are tutorials on that).  If not you need to 7unzip your dsf file in order that the script can read the dsf file.

**Comment by nofaceinbook** [comment]
So the all in one script is now working for me. I guess your issue is that you should 7unzip your dsf first.
In case of issues with XP12 because the material information is not found you could remove the lines adding the actual texture. They begin with "texImage.image = ..." and are in the function add_material(). In that case you would at least see the mesh triangles.

**Comment by nofaceinbook** [comment]
Oh my god, yes if the xplnedsf2.py is directly in addons it works. I never realzied it  as a had it there double in the past. Thanks for the hint.

**Comment by nofaceinbook** [comment]
Just to be sure. This tool is for converting the mesh dsf files and not is for the dsf files having information on the airport layout or where buildings are. Might be that the others don't have keys like sim/west.

**Comment by mendicus777** [comment]
Hi nofaceinbook,

many thanks once again for your efforts looking into this!
I was able to import a dsf (of course ;) I had to 7zip the .dsf beforehand), but the resolution is for my purposes way to low:

<img width="1431" alt="50_4" src="https://github.com/nofaceinbook/ImportDSF-for-Blender/assets/156319906/eeff82ae-f838-4d99-b425-4936b23c384a">


Sorry to bother - I know you mentioned you are not further developing for XP, but please allow one more question.
Would it be possible to import a .dsf so that you are able to zoom into the terrain with a lets say 1-10m resolution?

**Comment by mendicus777** [comment]
I converted now the .raw into a .txt and was able to import the Primitives into Blender (not sure if I am on the right approach)
Regardless, this is how it looks (if you are interested)

<img width="1458" alt="py_primitives" src="https://github.com/nofaceinbook/ImportDSF-for-Blender/assets/156319906/b23aa3d6-b1bf-4700-89b2-c22c072560cb">


I am not sure what the last two values are inside each VERTEX (I skipped them, as they are all the same)
PATCH_VERTEX 4.379816129 50.881235218 13.781250000 -0.000015259 -0.000015259

But I cannot view the elevation data I imported from the 3rd value inside the VERTEX

never mind - don't bother ;)
Thanks anyway!

**Comment by nofaceinbook** [comment]
Nice. Unfortunately I forgot all details of the dsf specification but there is a good document by Laminar on all details. I assume the values are details for the terrain. The elevation is stored separately. 

With regard to the resolution. There are several ways to change it. When importing you can set on the lower right some scaling factor and you can use blender functions to change it.
